#!/usr/bin/env python
"""Train a fermionic Born machine on the genomic SNV dataset.

The training objective and gradients use the repository's classical FBM
estimator. Piquasso's fermionic ``PureFockSimulator`` is used for every circuit
evaluation: checkpoint sampling, final sampling, and the final retained-qubit
probability vector.

Generated by ChatGPT 5.6 and using https://github.com/josephbowles/tcdq_genomic_coverage
as an input.

By default, five four-mode subsystems provide 20 physical/genomic data qubits,
with no discarded modes.

Run from the repository root with::

    python genomic_fbm_training.py
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parent
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

import jax

jax.config.update("jax_enable_x64", True)

import jax.numpy as jnp  # noqa: E402
import matplotlib  # noqa: E402

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import optax  # noqa: E402
import pennylane as qml  # noqa: E402
from tqdm.auto import tqdm  # noqa: E402

from src import (  # noqa: E402
    get_loss_and_grad_estimator,
    get_visible_qubits,
    set_seed,
)
from src.piquasso_utils import (  # noqa: E402
    get_fbm_probabilities,
    sample_fbm,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--n-subsystems", "--N", dest="N", type=int, default=5)
    parser.add_argument(
        "--discarded-qubits",
        type=int,
        nargs="*",
        default=[],
        metavar="Q",
        help=(
            "physical qubits to trace out (default: none); pass indices "
            "separated by spaces"
        ),
    )
    parser.add_argument("--eps", type=float, default=0.20)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--shots", type=int, default=5008)

    parser.add_argument("--n-layers", type=int, default=1)
    parser.add_argument("--steps", type=int, default=1000)
    parser.add_argument("--lr", type=float, default=0.001)
    parser.add_argument("--n-z-samples", type=int, default=256)
    parser.add_argument("--length-cutoff", type=int, default=5)
    parser.add_argument("--checkpoint-every", type=int, default=100)

    parser.add_argument("--smooth-window", type=int, default=100)
    parser.add_argument(
        "--out", default="genomic_fbm.png", type=Path
    )
    args = parser.parse_args()

    if args.n_layers < 1:
        parser.error("--n-layers must be positive")
    if args.steps < 1:
        parser.error("--steps must be positive")
    if args.shots < 1:
        parser.error("--shots must be positive")
    if args.checkpoint_every < 0:
        parser.error("--checkpoint-every cannot be negative")
    if args.smooth_window < 1:
        parser.error("--smooth-window must be positive")

    args.discarded_qubits = tuple(args.discarded_qubits)
    # Validate N and the discarded physical indices before loading the dataset.
    get_visible_qubits(args.N, args.discarded_qubits)
    return args


def pack(bits: np.ndarray, n_qubits: int) -> np.ndarray:
    """Pack bitstrings into int64 keys with data qubit 0 most significant."""
    powers = (1 << np.arange(n_qubits - 1, -1, -1)).astype(np.int64)
    return np.asarray(bits, dtype=np.int64) @ powers


def load_task(N: int, discarded_qubits, eps: float, seed: int) -> dict:
    """Build the same genomic train/valid/unseen task as the IQP script."""
    dataset = qml.data.load("other", name="genomic")[0]
    data = np.vstack([np.asarray(dataset.train), np.asarray(dataset.test)]).astype(
        np.int8
    )

    visible_qubits = get_visible_qubits(N, discarded_qubits)
    n_qubits = len(visible_qubits)
    if data.shape[1] < n_qubits:
        raise ValueError(
            f"The genomic dataset has {data.shape[1]} loci, but this FBM "
            f"configuration retains {n_qubits} qubits."
        )
    data = data[:, :n_qubits]

    valid_keys, counts = np.unique(pack(data, n_qubits), return_counts=True)
    target_probs = counts / counts.sum()

    n_train = int(eps * len(valid_keys))
    if not 0 < n_train <= len(data):
        raise ValueError(
            f"eps={eps} produces an invalid training size ({n_train}) for "
            f"{len(data)} genomic rows."
        )

    rng = np.random.default_rng(seed)
    train = data[rng.choice(len(data), n_train, replace=False)]
    train_keys = np.unique(pack(train, n_qubits))
    return {
        "n_qubits": n_qubits,
        "train": train,
        "valid_keys": valid_keys,
        "target_probs": target_probs,
        "unseen_keys": np.setdiff1d(valid_keys, train_keys),
    }


def init_weights(args: argparse.Namespace) -> jnp.ndarray:
    """Use the original FBM script's seeded uniform initialization."""
    n_physical_qubits = 4 * args.N
    majorana_dimension = 2 * n_physical_qubits
    weights_per_layer = majorana_dimension * (majorana_dimension - 1) // 2
    n_thetas = args.n_layers * weights_per_layer

    alphas = np.random.rand(args.N)
    thetas = np.random.rand(n_thetas)
    return jnp.asarray(np.concatenate([alphas, thetas]))


def sample_keys(
    weights,
    args: argparse.Namespace,
    seed: int,
) -> np.ndarray:
    """Sample retained FBM modes with Piquasso and pack them as keys."""
    samples = sample_fbm(
        args.N,
        np.asarray(weights[: args.N]),
        np.asarray(weights[args.N :]),
        args.shots,
        discarded_qubits=args.discarded_qubits,
        seed=seed,
    )
    return pack(samples, samples.shape[1])


def coverage(sampled_keys: np.ndarray, task: dict) -> float:
    """Return the fraction of unseen valid genomic strings sampled."""
    if len(task["unseen_keys"]) == 0:
        return 0.0
    hits = np.intersect1d(
        np.unique(sampled_keys), task["unseen_keys"], assume_unique=True
    )
    return len(hits) / len(task["unseen_keys"])


def train(
    task: dict,
    weights: jnp.ndarray,
    args: argparse.Namespace,
    sigma: float,
):
    """Train the FBM and evaluate Piquasso coverage at checkpoints."""
    optimizer = optax.adam(args.lr)
    opt_state = optimizer.init(weights)
    estimate_loss_and_grad = get_loss_and_grad_estimator(
        sigmas=[sigma],
        no_of_Z_samples=args.n_z_samples,
        N=args.N,
        training_set=task["train"],
        length_cutoff=args.length_cutoff,
        discarded_qubits=args.discarded_qubits,
    )

    losses = []
    checkpoints = []
    progress = tqdm(range(1, args.steps + 1), desc="training FBM", unit="step")
    for step in progress:
        loss, loss_grad = estimate_loss_and_grad(weights)
        updates, opt_state = optimizer.update(loss_grad, opt_state)
        weights = optax.apply_updates(weights, updates)
        losses.append(float(loss))
        progress.set_postfix(loss=f"{losses[-1]:.4e}", refresh=False)

        if args.checkpoint_every and step % args.checkpoint_every == 0:
            keys = sample_keys(weights, args, seed=args.seed)
            checkpoint = (step, coverage(keys, task))
            checkpoints.append(checkpoint)
            progress.set_postfix(
                loss=f"{losses[-1]:.4e}", coverage=f"{checkpoint[1]:.4f}"
            )
            tqdm.write(
                f"  step {step:>5}/{args.steps}  loss = {losses[-1]:.4e}  "
                f"C = {checkpoint[1]:.4f}"
            )

    return weights, np.asarray(losses), checkpoints


def evaluate(weights, task: dict, args: argparse.Namespace) -> tuple[dict, np.ndarray]:
    """Compute final sample and probability metrics using Piquasso."""
    keys = sample_keys(weights, args, seed=args.seed + 1000)
    probabilities = get_fbm_probabilities(
        args.N,
        np.asarray(weights[: args.N]),
        np.asarray(weights[args.N :]),
        discarded_qubits=args.discarded_qubits,
    )

    valid = np.isin(keys, task["valid_keys"])
    train_keys = pack(task["train"], task["n_qubits"])
    new = ~np.isin(keys, train_keys)
    q_valid = probabilities[task["valid_keys"]]
    with np.errstate(divide="ignore", invalid="ignore"):
        forward_kl = float(
            np.sum(task["target_probs"] * np.log(task["target_probs"] / q_valid))
        )

    metrics = {
        "coverage": coverage(keys, task),
        "fidelity": float((valid & new).sum() / max(new.sum(), 1)),
        "valid_mass": float(q_valid.sum()),
        "forward_kl": forward_kl,
        "random_coverage": 1.0
        - (1.0 - 2.0 ** (-task["n_qubits"])) ** args.shots,
    }
    return metrics, probabilities


def rolling_median(values: np.ndarray, window: int) -> np.ndarray:
    """Return a centred rolling median truncated at the array edges."""
    half = window // 2
    return np.asarray(
        [
            np.median(values[max(0, index - half) : index + half + 1])
            for index in range(len(values))
        ]
    )


def plot(losses, checkpoints, args: argparse.Namespace, sigma: float) -> None:
    """Plot training loss and checkpoint coverage like the IQP script."""
    fig, ax = plt.subplots(figsize=(7.2, 4.3))
    series = rolling_median(losses, args.smooth_window)
    steps = np.arange(1, len(losses) + 1)

    ax.plot(
        steps,
        losses,
        color="0.72",
        lw=0.8,
        zorder=1,
        label="MMD$^2$ estimate per step",
    )
    ax.plot(
        steps,
        series,
        color="0.12",
        lw=2.0,
        zorder=3,
        label=f"MMD$^2$ (rolling median, {args.smooth_window} steps)",
    )

    positive = np.concatenate([losses[losses > 0], series[series > 0]])
    if len(positive):
        ax.set_yscale("log")
        ax.set_ylim(positive.min() * 0.5, positive.max() * 2.0)
    ax.set_xlabel("training step")
    ax.set_ylabel("FBM training loss")
    n_visible = len(get_visible_qubits(args.N, args.discarded_qubits))
    ax.set_title(
        f"Fermionic Born machine, genomic task, $N={args.N}$, "
        f"{4 * args.N} physical / {n_visible} data qubits, "
        f"$\\sigma={sigma:.3f}$",
        fontsize=10.5,
    )

    handles, labels = ax.get_legend_handles_labels()
    if checkpoints:
        checkpoint_steps, coverage_values = zip(*checkpoints)
        random_coverage = 1.0 - (1.0 - 2.0**-n_visible) ** args.shots
        twin = ax.twinx()
        twin.plot(
            checkpoint_steps,
            coverage_values,
            color="crimson",
            marker="o",
            ms=4.5,
            lw=1.6,
            label="coverage $C$",
        )
        twin.axhline(
            random_coverage,
            color="crimson",
            ls="--",
            lw=1.2,
            label="random-bit floor $C_{\\rm rand}$",
        )
        twin.set_ylabel("coverage $C$", color="crimson")
        twin.tick_params(axis="y", labelcolor="crimson")
        upper = max(max(coverage_values), random_coverage) * 1.9
        twin.set_ylim(0, min(1.0, max(upper, 1e-3)))
        extra_handles, extra_labels = twin.get_legend_handles_labels()
        handles += extra_handles
        labels += extra_labels

    ax.legend(
        handles,
        labels,
        loc="lower left",
        fontsize=8.5,
        frameon=False,
        ncol=2,
    )
    fig.tight_layout()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(args.out, dpi=170)
    plt.close(fig)
    print(f"wrote {args.out}")


def main() -> None:
    args = parse_args()
    set_seed(args.seed)

    task = load_task(args.N, args.discarded_qubits, args.eps, args.seed)
    sigma = 1.0
    weights = init_weights(args)

    print(
        f"N={args.N}  physical={4 * args.N}  data={task['n_qubits']}  "
        f"|S|={len(task['valid_keys']):,}  |T|={len(task['train']):,}  "
        f"|U|={len(task['unseen_keys']):,}  params={len(weights):,}  "
        f"sigma={sigma:.4f}"
    )

    weights, losses, checkpoints = train(task, weights, args, sigma)

    print("Computing final Piquasso samples and probability vector...")
    metrics, probabilities = evaluate(weights, task, args)
    print(
        f"\ncoverage C   = {metrics['coverage']:.4f}   "
        f"(random-bit floor {metrics['random_coverage']:.4f})\n"
        f"fidelity F   = {metrics['fidelity']:.4f}\n"
        f"valid mass   = {metrics['valid_mass']:.4f}\n"
        f"forward KL   = {metrics['forward_kl']:.4f}"
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    np.savez(
        args.out.with_suffix(".npz"),
        weights=np.asarray(weights),
        losses=losses,
        checkpoints=np.asarray(checkpoints, dtype=float),
        probabilities=probabilities,
        discarded_qubits=np.asarray(args.discarded_qubits, dtype=int),
        **metrics,
    )
    plot(losses, checkpoints, args, sigma)


if __name__ == "__main__":
    main()
