import numpy as np

import numba as nb

import jax
import jax.numpy as jnp

from functools import partial

from src.piquasso_utils import (
    next_first_quantized,
    get_fock_subspace_dimension,
    to_first_quantized,
)


def _random_bitstring(n, k):
    """Generates a random bitstring of length n with exactly k ones."""
    bitstring = np.zeros(n, dtype=int)
    bitstring[:k] = 1
    np.random.shuffle(bitstring)
    return bitstring


def random_first_quantized_majorana_string(d, locality):
    return to_first_quantized(_random_bitstring(d, locality))


@nb.njit(cache=True)
def iterate_first_quantized_on_fock_subspace(d, locality):
    string = np.arange(locality)
    size = get_fock_subspace_dimension(d, locality)

    for _ in range(size):
        yield string.copy()
        string = next_first_quantized(string, d)


def get_first_quantized_vectors(d, locality):
    return np.array(list(iterate_first_quantized_on_fock_subspace(d, locality)))


@nb.njit(cache=True)
def expand_to_Z(string):
    doubled = 2 * string
    added_one = doubled + 1
    result = np.empty(2 * len(string), dtype=nb.int32)
    result[0::2] = doubled
    result[1::2] = added_one
    return result


@nb.njit(cache=True)
def pad_majorana_string(string, n_bits_local_m_1):
    # padding a 4-bit Z-string to a 5-bit one.
    return string + string // n_bits_local_m_1 + 1


def map_visible_to_physical(string, visible_qubits):
    """Map indices in the retained data space to physical circuit qubits."""
    return np.asarray(visible_qubits, dtype=int)[np.asarray(string, dtype=int)]


def calculate_relevant_Z_strings_on_subspace(
    n_bits, Z_locality, N, discarded_qubits=None
):
    from src.utils import get_visible_qubits

    if n_bits != 4 * N:
        raise ValueError(f"Expected n_bits=4*N={4 * N}, got {n_bits}.")
    visible_qubits = get_visible_qubits(N, discarded_qubits)
    small_d_over_2 = len(visible_qubits)

    size = get_fock_subspace_dimension(small_d_over_2, Z_locality)

    Z_strings = np.empty((size, 2 * Z_locality), dtype=int)

    for idx, string in enumerate(
        iterate_first_quantized_on_fock_subspace(small_d_over_2, Z_locality)
    ):
        physical_string = map_visible_to_physical(string, visible_qubits)
        Z_strings[idx] = expand_to_Z(physical_string)

    return Z_strings


@partial(jax.jit, static_argnums=(0,))  #  ← n is treated as compile-time
def four_ary_array(n: int, dtype=jnp.uint8) -> jnp.ndarray:
    """
    Return an array of shape (4**n, n) whose rows list every length-n
    base-4 vector in lexicographic order.
    JIT-compiled; JAX will cache one kernel per distinct n value.

    Generated by ChatGPT.
    """
    total = 4**n  # scalar -- OK, static
    numbers = jnp.arange(total)  # (4**n,)
    powers = 4 ** jnp.arange(n - 1, -1, -1)  # (n,)

    return ((numbers[:, None] // powers) % 4).astype(dtype)
